task:
    freebsd_instance:
      matrix:
        - image: freebsd-12-1-release-amd64
        - image: freebsd-12-2-release-amd64

    build_script: ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    install_script: make BATCH=yes package
    binaries_artifacts:
        path: "work/pkg/*"
