freebsd_instance:
    image_family: freebsd-12-2

task:
    build_script: ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    install_script: make BATCH=yes package
    binaries_artifacts:
        path: "work/pkg/*"
